### PR TITLE
Prove get_step `~>` current_state_matches for all subresources of rabbitmq

### PR DESCRIPTION
**Pull request by euclidgame**
This PR also proves the stability. After proving these, the left to do is as follows:

- Prove that `init ~> get_step` for all sub resources, which should be straightforward.
- Combine all subresources and derive the overall `current_state_matches` state.
- Put all the invariants in good order.
- Prove all the invariants.

### CODE REVIEW

**Comment by marshtompsxd** [comment]
It seems that I forgot to pin Verus version for unit test. I will send a PR to fix it right now

**Comment by marshtompsxd** [comment]
You can rebase and push again after #324 is merged

**Comment by euclidgame** [comment]
No worries. Just WIP.

**Comment by euclidgame** [comment]
I comment some validation rules to make the proof easier. Maybe recover them later.

**Comment by marshtompsxd** [comment]
is this ready to be reviewed?

**Pull request merged**
