### PR TITLE
Fix simple controller liveness proof: Prove `after_create_cm_pc ~> cm_always_exists`

### PR DESCRIPTION
**Pull request by euclidgame**
Prove the lemma `simple_controller::proof::liveness::lemma_after_create_cm_pc_leads_to_cm_always_exists`. This lemma ensures that after a custom resource is added to the ongoing reconciles of the controller, it will eventually appear and always exists in the resources of k8s api.

### CODE REVIEW

**Comment by tianyin** [comment]
WoW this is @euclidgame 's first merged PR! Good job!!

**Comment by euclidgame** [comment]
Thank you so much @tianyin !!!!!

**Comment by lalithsuresh** [comment]
That was quick, welcome @euclidgame !

**Comment by euclidgame** [comment]
Thanks, @lalithsuresh !!!

**Pull request merged**
